const moodSeed = [
  { id: "happy", label: "Happy", icon: "smile", order: 1, active: true },
  { id: "romantic", label: "Romantic", icon: "heart", order: 2, active: true },
  { id: "relaxed", label: "Relaxed", icon: "leaf", order: 3, active: true },
  { id: "tired", label: "Tired", icon: "moon", order: 4, active: true },
  { id: "stressed", label: "Stressed", icon: "bolt", order: 5, active: true },
  { id: "playful", label: "Playful", icon: "spark", order: 6, active: true },
  { id: "nostalgic", label: "Nostalgic", icon: "clock", order: 7, active: true },
  { id: "adventurous", label: "Adventurous", icon: "compass", order: 8, active: true },
  { id: "elegant", label: "Elegant", icon: "gem", order: 9, active: true },
  { id: "health-conscious", label: "Health-conscious", icon: "seed", order: 10, active: true }
];

const occasionSeed = [
  { id: "date-night", label: "Date night", icon: "heart", order: 1, active: true },
  { id: "family-outing", label: "Family outing", icon: "group", order: 2, active: true },
  { id: "birthday", label: "Birthday", icon: "cake", order: 3, active: true },
  { id: "hot-afternoon", label: "Hot afternoon", icon: "sun", order: 4, active: true },
  { id: "business-meeting", label: "Business meeting", icon: "briefcase", order: 5, active: true },
  { id: "weekend-treat", label: "Weekend treat", icon: "spark", order: 6, active: true },
  { id: "festive-celebration", label: "Festive celebration", icon: "star", order: 7, active: true },
  { id: "kids-party", label: "Kids party", icon: "balloon", order: 8, active: true },
  { id: "solo-comfort-treat", label: "Solo comfort treat", icon: "mug", order: 9, active: true }
];

const flavourSeed = [
  {
    id: "pistachio-supreme",
    flavourName: "Pistachio Supreme",
    productType: "gelato",
    status: "active",
    description: "Premium pistachio gelato with a deep roasted finish.",
    image: "",
    baseTasteTags: ["creamy", "nutty", "indulgent"],
    moodTags: ["happy", "romantic", "elegant", "mature"],
    occasionTags: ["date-night", "business-meeting", "birthday", "festive-celebration"],
    dietaryTags: [],
    weatherSuitability: ["anytime", "rainy day"],
    recommendedToppings: ["pistachio dust", "biscotti crumble"],
    basePrice: 10.5,
    priorityScore: 90,
    upsellScore: 95,
    marginScore: 88,
    popularityScore: 86,
    stockStatus: "in_stock",
    activeImage: ""
  },
  {
    id: "dark-chocolate",
    flavourName: "Dark Chocolate",
    productType: "gelato",
    status: "active",
    description: "Rich, grounding dark chocolate for comfort-driven orders.",
    image: "",
    baseTasteTags: ["chocolatey", "indulgent", "creamy"],
    moodTags: ["stressed", "tired", "nostalgic", "elegant"],
    occasionTags: ["business-meeting", "solo-comfort-treat", "date-night"],
    dietaryTags: [],
    weatherSuitability: ["rainy day", "anytime"],
    recommendedToppings: ["chocolate curls", "brownie crumble"],
    basePrice: 9.8,
    priorityScore: 84,
    upsellScore: 78,
    marginScore: 82,
    popularityScore: 90,
    stockStatus: "in_stock",
    activeImage: ""
  },
  {
    id: "vanilla-bean",
    flavourName: "Vanilla Bean",
    productType: "gelato",
    status: "active",
    description: "Classic vanilla bean with a smooth premium body.",
    image: "",
    baseTasteTags: ["creamy", "light"],
    moodTags: ["romantic", "relaxed", "nostalgic", "kids"],
    occasionTags: ["family-outing", "kids-party", "date-night"],
    dietaryTags: [],
    weatherSuitability: ["anytime"],
    recommendedToppings: ["fresh berries", "biscotti crumble"],
    basePrice: 8.9,
    priorityScore: 76,
    upsellScore: 66,
    marginScore: 71,
    popularityScore: 94,
    stockStatus: "in_stock",
    activeImage: ""
  },
  {
    id: "strawberry-bliss",
    flavourName: "Strawberry Bliss",
    productType: "gelato",
    status: "active",
    description: "Bright strawberry gelato built for joyful sharing moments.",
    image: "",
    baseTasteTags: ["fruity", "light"],
    moodTags: ["happy", "romantic", "playful", "kids"],
    occasionTags: ["birthday", "date-night", "kids-party"],
    dietaryTags: [],
    weatherSuitability: ["hot day", "anytime"],
    recommendedToppings: ["fresh berries", "chocolate curls"],
    basePrice: 9.2,
    priorityScore: 75,
    upsellScore: 72,
    marginScore: 69,
    popularityScore: 82,
    stockStatus: "in_stock",
    activeImage: ""
  },
  {
    id: "mango-sorbet",
    flavourName: "Mango Sorbet",
    productType: "sorbet",
    status: "active",
    description: "Refreshing mango sorbet for hot days and mood-lifting orders.",
    image: "",
    baseTasteTags: ["fruity", "refreshing", "light", "tangy"],
    moodTags: ["happy", "tired", "playful", "health-conscious"],
    occasionTags: ["hot-afternoon", "weekend-treat", "family-outing"],
    dietaryTags: ["dairy-free", "vegan", "lactose intolerant friendly"],
    weatherSuitability: ["hot day"],
    recommendedToppings: ["fresh berries", "mint leaves", "citrus zest"],
    basePrice: 8.7,
    priorityScore: 88,
    upsellScore: 61,
    marginScore: 79,
    popularityScore: 91,
    stockStatus: "in_stock",
    activeImage: ""
  },
  {
    id: "lemon-yuzu-sorbet",
    flavourName: "Lemon Yuzu Sorbet",
    productType: "sorbet",
    status: "active",
    description: "Sharp citrus sorbet for heat and palate-cleansing moments.",
    image: "",
    baseTasteTags: ["refreshing", "tangy", "light"],
    moodTags: ["tired", "health-conscious", "elegant"],
    occasionTags: ["hot-afternoon", "business-meeting", "festive-celebration"],
    dietaryTags: ["dairy-free", "vegan", "lactose intolerant friendly", "low added sugar"],
    weatherSuitability: ["hot day"],
    recommendedToppings: ["citrus zest", "mint leaves"],
    basePrice: 8.9,
    priorityScore: 86,
    upsellScore: 58,
    marginScore: 77,
    popularityScore: 80,
    stockStatus: "in_stock",
    activeImage: ""
  },
  {
    id: "coconut-pandan",
    flavourName: "Coconut Pandan",
    productType: "gelato",
    status: "seasonal",
    description: "A festive pandan-coconut profile with soft tropical depth.",
    image: "",
    baseTasteTags: ["creamy", "floral", "light"],
    moodTags: ["relaxed", "nostalgic", "festive"],
    occasionTags: ["festive-celebration", "family-outing", "weekend-treat"],
    dietaryTags: [],
    weatherSuitability: ["anytime", "hot day"],
    recommendedToppings: ["toasted coconut", "biscotti crumble"],
    basePrice: 9.6,
    priorityScore: 81,
    upsellScore: 73,
    marginScore: 75,
    popularityScore: 74,
    stockStatus: "in_stock",
    activeImage: ""
  },
  {
    id: "coffee-crunch",
    flavourName: "Coffee Crunch",
    productType: "gelato",
    status: "active",
    description: "Coffee gelato with depth and a subtle roasted finish.",
    image: "",
    baseTasteTags: ["coffee", "indulgent", "creamy"],
    moodTags: ["tired", "stressed", "elegant"],
    occasionTags: ["business-meeting", "after-dinner", "weekend-treat"],
    dietaryTags: ["contains caffeine"],
    weatherSuitability: ["anytime", "rainy day"],
    recommendedToppings: ["biscotti crumble", "chocolate curls"],
    basePrice: 9.7,
    priorityScore: 80,
    upsellScore: 76,
    marginScore: 81,
    popularityScore: 83,
    stockStatus: "in_stock",
    activeImage: ""
  },
  {
    id: "hojicha",
    flavourName: "Hojicha",
    productType: "gelato",
    status: "active",
    description: "Toasted tea notes for peaceful and refined moments.",
    image: "",
    baseTasteTags: ["tea", "light", "elegant"],
    moodTags: ["relaxed", "elegant", "health-conscious"],
    occasionTags: ["weekend-treat", "business-meeting", "solo-comfort-treat"],
    dietaryTags: ["contains caffeine"],
    weatherSuitability: ["anytime", "rainy day"],
    recommendedToppings: ["biscotti crumble", "toasted coconut"],
    basePrice: 9.4,
    priorityScore: 72,
    upsellScore: 68,
    marginScore: 73,
    popularityScore: 69,
    stockStatus: "in_stock",
    activeImage: ""
  },
  {
    id: "watermelon-granita",
    flavourName: "Watermelon Granita",
    productType: "granita",
    status: "active",
    description: "Cooling granita for tropical weather and thirsty guests.",
    image: "",
    baseTasteTags: ["refreshing", "fruity", "light"],
    moodTags: ["tired", "health-conscious", "playful"],
    occasionTags: ["hot-afternoon", "festive-celebration", "kids-party"],
    dietaryTags: ["dairy-free", "vegan", "lactose intolerant friendly", "low added sugar"],
    weatherSuitability: ["hot day"],
    recommendedToppings: ["mint leaves", "citrus zest"],
    basePrice: 7.8,
    priorityScore: 84,
    upsellScore: 48,
    marginScore: 69,
    popularityScore: 72,
    stockStatus: "in_stock",
    activeImage: ""
  },
  {
    id: "lychee-rose-sorbet",
    flavourName: "Lychee Rose Sorbet",
    productType: "sorbet",
    status: "active",
    description: "Floral-fruit sorbet for elegant or romantic occasions.",
    image: "",
    baseTasteTags: ["floral", "fruity", "refreshing", "light"],
    moodTags: ["romantic", "playful", "elegant"],
    occasionTags: ["date-night", "festive-celebration", "weekend-treat"],
    dietaryTags: ["dairy-free", "vegan", "lactose intolerant friendly"],
    weatherSuitability: ["hot day", "anytime"],
    recommendedToppings: ["fresh berries", "citrus zest"],
    basePrice: 9.1,
    priorityScore: 79,
    upsellScore: 70,
    marginScore: 74,
    popularityScore: 76,
    stockStatus: "in_stock",
    activeImage: ""
  }
];

const toppingSeed = [
  {
    id: "pistachio-dust",
    toppingName: "Pistachio dust",
    description: "Premium nutty finish for elegant scoops.",
    priceAddOn: 1.8,
    compatibilityTags: ["premium", "nutty", "gelato"],
    dietaryTags: [],
    status: "active",
    image: "",
    upsellPriority: 92,
    stockStatus: "in_stock"
  },
  {
    id: "chocolate-curls",
    toppingName: "Chocolate curls",
    description: "A premium chocolate garnish for indulgent builds.",
    priceAddOn: 1.5,
    compatibilityTags: ["indulgent", "chocolatey", "romantic"],
    dietaryTags: [],
    status: "active",
    image: "",
    upsellPriority: 88,
    stockStatus: "in_stock"
  },
  {
    id: "brownie-crumble",
    toppingName: "Brownie crumble",
    description: "Dense fudgy crunch for comfort-led profiles.",
    priceAddOn: 1.9,
    compatibilityTags: ["comforting", "indulgent", "coffee"],
    dietaryTags: [],
    status: "active",
    image: "",
    upsellPriority: 84,
    stockStatus: "in_stock"
  },
  {
    id: "toasted-coconut",
    toppingName: "Toasted coconut",
    description: "Crisp tropical finish.",
    priceAddOn: 1.2,
    compatibilityTags: ["tropical", "light", "sorbet"],
    dietaryTags: ["vegan"],
    status: "active",
    image: "",
    upsellPriority: 63,
    stockStatus: "in_stock"
  },
  {
    id: "fresh-berries",
    toppingName: "Fresh berries",
    description: "Bright fruit accent.",
    priceAddOn: 1.7,
    compatibilityTags: ["fruit", "romantic", "light"],
    dietaryTags: ["vegan"],
    status: "active",
    image: "",
    upsellPriority: 74,
    stockStatus: "in_stock"
  },
  {
    id: "biscotti-crumble",
    toppingName: "Biscotti crumble",
    description: "Crisp, premium crunch for gelato.",
    priceAddOn: 1.4,
    compatibilityTags: ["premium", "coffee", "gelato"],
    dietaryTags: [],
    status: "active",
    image: "",
    upsellPriority: 78,
    stockStatus: "in_stock"
  },
  {
    id: "mint-leaves",
    toppingName: "Mint leaves",
    description: "Clean cooling garnish for sorbet and granita.",
    priceAddOn: 0.8,
    compatibilityTags: ["refreshing", "granita", "sorbet"],
    dietaryTags: ["vegan"],
    status: "active",
    image: "",
    upsellPriority: 52,
    stockStatus: "in_stock"
  },
  {
    id: "citrus-zest",
    toppingName: "Citrus zest",
    description: "Aromatic lift for bright profiles.",
    priceAddOn: 0.9,
    compatibilityTags: ["refreshing", "fruit", "light"],
    dietaryTags: ["vegan"],
    status: "active",
    image: "",
    upsellPriority: 58,
    stockStatus: "in_stock"
  }
];

const matrixRuleSeed = [
  {
    id: "rule-happy-celebratory",
    name: "Happy / celebratory",
    mood: "happy",
    occasion: "birthday",
    weather: "",
    recommendedBase: "gelato",
    includeTags: ["indulgent", "premium", "creamy", "nutty", "chocolatey"],
    excludeTags: [],
    toppingDirection: ["chocolate curls", "biscotti crumble", "pistachio dust"],
    why: "Indulgent, premium feel",
    examples: ["Pistachio Supreme", "Dark Chocolate"],
    weightBoost: 16,
    enabled: true,
    note: "Seeded from spreadsheet"
  },
  {
    id: "rule-romantic-intimate",
    name: "Romantic / intimate",
    mood: "romantic",
    occasion: "date-night",
    weather: "",
    recommendedBase: "gelato",
    includeTags: ["creamy", "floral", "light"],
    excludeTags: [],
    toppingDirection: ["fresh berries", "chocolate curls", "pistachio dust"],
    why: "Smooth, luxurious texture",
    examples: ["Vanilla Bean", "Lychee Rose Sorbet"],
    weightBoost: 15,
    enabled: true,
    note: "Seeded from spreadsheet"
  },
  {
    id: "rule-relaxed-hot",
    name: "Relaxed / peaceful",
    mood: "relaxed",
    occasion: "weekend-treat",
    weather: "",
    recommendedBase: "gelato|sorbet",
    includeTags: ["light", "tea", "floral", "refreshing"],
    excludeTags: [],
    toppingDirection: ["fresh berries", "toasted coconut", "biscotti crumble"],
    why: "Gentle flavours feel calming",
    examples: ["Hojicha", "Vanilla Bean"],
    weightBoost: 13,
    enabled: true,
    note: "Seeded from spreadsheet"
  },
  {
    id: "rule-tired-overheated",
    name: "Tired / overheated",
    mood: "tired",
    occasion: "hot-afternoon",
    weather: "hot day",
    recommendedBase: "sorbet",
    includeTags: ["refreshing", "fruity", "tangy", "light"],
    excludeTags: ["indulgent"],
    toppingDirection: ["mint leaves", "citrus zest", "fresh berries"],
    why: "Refreshing, clean finish",
    examples: ["Mango Sorbet", "Lemon Yuzu Sorbet"],
    weightBoost: 18,
    enabled: true,
    note: "Seeded from spreadsheet"
  },
  {
    id: "rule-thirsty-heat-stressed",
    name: "Thirsty / heat-stressed",
    mood: "health-conscious",
    occasion: "hot-afternoon",
    weather: "hot day",
    recommendedBase: "granita",
    includeTags: ["refreshing", "light", "fruity"],
    excludeTags: ["indulgent"],
    toppingDirection: ["mint leaves", "citrus zest"],
    why: "Most cooling feel",
    examples: ["Watermelon Granita"],
    weightBoost: 19,
    enabled: true,
    note: "Avoid heavy toppings"
  },
  {
    id: "rule-stressed-mentally-drained",
    name: "Stressed / mentally drained",
    mood: "stressed",
    occasion: "solo-comfort-treat",
    weather: "",
    recommendedBase: "gelato",
    includeTags: ["chocolatey", "coffee", "indulgent", "creamy"],
    excludeTags: [],
    toppingDirection: ["brownie crumble", "chocolate curls", "biscotti crumble"],
    why: "Comforting and grounding",
    examples: ["Dark Chocolate", "Coffee Crunch"],
    weightBoost: 17,
    enabled: true,
    note: "Seeded from spreadsheet"
  },
  {
    id: "rule-comfort-nostalgic",
    name: "Comfort / nostalgic",
    mood: "nostalgic",
    occasion: "family-outing",
    weather: "rainy day",
    recommendedBase: "gelato",
    includeTags: ["creamy", "light", "chocolatey"],
    excludeTags: [],
    toppingDirection: ["biscotti crumble", "toasted coconut"],
    why: "Familiar flavours, warm feel",
    examples: ["Vanilla Bean", "Dark Chocolate", "Coconut Pandan"],
    weightBoost: 15,
    enabled: true,
    note: "Seeded from spreadsheet"
  },
  {
    id: "rule-playful-adventurous",
    name: "Playful / adventurous",
    mood: "adventurous",
    occasion: "weekend-treat",
    weather: "",
    recommendedBase: "gelato|sorbet",
    includeTags: ["fruity", "floral", "tea", "refreshing"],
    excludeTags: [],
    toppingDirection: ["toasted coconut", "fresh berries"],
    why: "Contrast feels exciting",
    examples: ["Lychee Rose Sorbet", "Mango Sorbet"],
    weightBoost: 14,
    enabled: true,
    note: "Seeded from spreadsheet"
  }
];

const recommendationWeights = {
  mood: 26,
  preference: 24,
  occasion: 16,
  weather: 14,
  priority: 10,
  upsell: 4,
  popularity: 3,
  margin: 3
};

export const initialState = {
  flavours: flavourSeed,
  moods: moodSeed,
  occasions: occasionSeed,
  toppings: toppingSeed,
  rules: matrixRuleSeed,
  weights: recommendationWeights,
  sessions: [],
  cart: [],
  feedback: [],
  shareEvents: [],
  analyticsEvents: []
};
